### ISSUE TITLE
feature: DGS client generated code does not allow arguments to be specified inside query path

### ISSUE THREAD

**Issue by nick-stephen** [Netflix/dgs-framework#547]
## Describe the Feature Request

DGS client generated code does not allow users to specify input arguments to projections even though they are specified in the schema.

This prevents users from being able to use the generated client code as we cannot formulate our queries properly.

This is really a limitation or bug in the generated client code. I filed under feature request though.

For example, given the schema below:

```
type Query {
	one: One
}

type One {
	two(three: Three!): Two
}

type Two {
	test: String
}

input Three {
	test3: String
}
```

It is not possible to formulate a query of the form:

```
{
    one {
        two(three: {
            test3: "argument"
        }) {
            test
        }
    }
}
```

The closest I could come with the generated client code was this - but it doesn't let me specify an argument for the 'two' field of type 'One', and so this query will fail:

```
        GraphQLQueryRequest request = new GraphQLQueryRequest(
                new OneGraphQLQuery.Builder()
                        .build(),
                new OneProjectionRoot()
                        .two()
                        .test());
```

## Describe Preferred Solution

I believe that the `OneProjectionRoot.two()` method should take an argument of type `Three`) and given the `!` mark, should validate that it is non-null.

For backward compatibility we could leave the no-arg method in place and have it invoke this new method with a null argument.

This would allow clients to build their graphQL requests much more easily.

## Describe Alternatives

This seems like the best approach. Adding alternative GraphQLQuery classes for each specific case seems the wrong alternative.

--
This request was also raised as a discussion by another user here:

https://github.com/Netflix/dgs-framework/discussions/370

**Comment by paulbakker** [comment]
I'm wondering if you're using an older version of codegen, because this should be supported. This was fixed not too long ago.

See an example here: https://github.com/Netflix/dgs-examples-kotlin/blob/main/src/test/kotlin/com/example/demo/datafetchers/ShowsDataFetcherTest.kt#L130

I'm closing this, assuming it's just an outdated codegen, but feel free to re-open if there turns out to be an issue.

**Comment by berngp** [comment]
@nick-stephen with the latest [codegen plugin](https://github.com/Netflix/dgs-codegen) you should get

```
public class OneGraphQLQuery extends GraphQLQuery {
  public OneGraphQLQuery() {
    super("query");
  }

  @Override
  public String getOperationName() {
    return "one";
  }

  public static Builder newRequest() {
    return new Builder();
  }

  public static class Builder {
    private Set<String> fieldsSet = new HashSet<>();

    public OneGraphQLQuery build() {
      return new OneGraphQLQuery();
    }
  }
}

public class OneProjectionRoot extends BaseProjectionNode {
  public One_TwoProjection two() {
    One_TwoProjection projection = new One_TwoProjection(this, this);
    getFields().put("two", projection);
    return projection;
  }

  public One_TwoProjection two(Three three) {
    One_TwoProjection projection = new One_TwoProjection(this, this);
    getFields().put("two", projection);
    getInputArguments().computeIfAbsent("two", k -> new ArrayList<>());
    InputArgument threeArg = new InputArgument("three", three);
        getInputArguments().get("two").add(threeArg);
    return projection;
  }
}

public class One_TwoProjection extends BaseSubProjectionNode<OneProjectionRoot, OneProjectionRoot> {
  public One_TwoProjection(OneProjectionRoot parent, OneProjectionRoot root) {
    super(parent, root, java.util.Optional.of("Two"));
  }

  public One_TwoProjection test() {
    getFields().put("test", null);
    return this;
  }
}
```

**Comment by berngp** [comment]
Note we don't validate nullability.

**Comment by nick-stephen** [comment]
Thank you, yes, this trivial example use case now works, however a slightly more complex use-case still fails. 

I opened a separate bug for this: https://github.com/Netflix/dgs-framework/issues/548
